{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "009c8b77",
   "metadata": {},
   "outputs": [],
   "source": [
    "from pycaret.regression import *\n",
    "import pandas as pd \n",
    "import numpy as np\n",
    "import streamlit as st\n",
    "from PIL import Image\n",
    "import os\n",
    "\n",
    "class StreamlitApp:\n",
    "    \n",
    "    def __init__(self):\n",
    "        self.model = load_model('model/final_model_house_prices') \n",
    "        self.save_fn = 'path.csv'     \n",
    "        \n",
    "    def predict(self, input_data): \n",
    "        return predict_model(self.model, data=input_data)\n",
    "    \n",
    "    def store_prediction(self, output_df): \n",
    "        if os.path.exists(self.save_fn):\n",
    "            save_df = pd.read_csv(self.save_fn)\n",
    "            save_df = save_df.append(output_df, ignore_index=True)\n",
    "            save_df.to_csv(self.save_fn, index=False)\n",
    "            \n",
    "        else: \n",
    "            output_df.to_csv(self.save_fn, index=False)  \n",
    "            \n",
    "    \n",
    "    def run(self):\n",
    "        image = Image.open('assets/hus.jpg')\n",
    "        st.image(image, use_column_width=False)\n",
    "    \n",
    "    \n",
    "        add_selectbox = st.sidebar.selectbox('How would you like to predict?', ('Online', 'Batch'))  \n",
    "        st.sidebar.info('This app is created to predict houseprices' )\n",
    "        st.sidebar.success('DAT158')\n",
    "        st.title('Housing Prices')\n",
    "        \n",
    "       \n",
    "        if add_selectbox == 'Online':\n",
    "            OverallQual = st.number_input('OverallQual', min_value=1, max_value=10, value=5)\n",
    "            MSZoning = st.selectbox('MSZoning', ['A', 'C', 'FV', 'I', 'RH', 'RL', 'RP','RM'])\n",
    "            GrLivArea = st.number_input('GrLivArea', min_value=300, max_value=6000, value=1500)\n",
    "            OverallCond = st.number_input('OverallCond', min_value=1, max_value=9, value=5)           \n",
    "            GarageType = st.selectbox('GarageType', ['2Types', 'Attchd', 'Basment', 'BuiltIn', 'CarPort', 'Detchd', 'NA'])\n",
    "            LandSlope = st.selectbox('LandSlope', ['Gtl', 'Mod', 'Sev'])\n",
    "            FullBath = st.number_input('FullBath', min_value=0, max_value=5, value=0) \n",
    "            Neighborhood = st.selectbox('Neighborhood', ['Blmngtn', 'Blueste', 'BrDale', 'BrkSide', 'ClearCr', \n",
    "                                                         'CollgCr', 'Crawfor', 'Edwards', 'Gilbert', 'IDOTRR', \n",
    "                                                         'MeadowV', 'Mitchel', 'Names','NoRidge', 'NPkVill', \n",
    "                                                         'NridgHt', 'NWAmes', 'OldTown','SWISU', 'Sawyer', \n",
    "                                                         'SawyerW', 'Somerst', 'StoneBr', 'Timber', 'Veenker', 'Up', 'Down'])\n",
    "            Functional = st.selectbox('Functional', ['Typ', 'Min1', 'Min2', 'Mod', 'Maj1', 'Maj2', 'Sev', 'Sal'])\n",
    "            GarageCars =st.number_input('GarageCars', min_value=0.0, max_value=10.0, value=1.0)\n",
    "            GarageArea = st.number_input('GarageArea', min_value=0.0, max_value=2000.0, value=1000.0)\n",
    "            TotRmsAbvGrd = st.number_input('TotRmsAbvGrd', min_value=1.0, max_value=30.0, value=6.0)\n",
    "            Fireplaces = st.number_input('Fireplaces', min_value=1.0, max_value=5.0, value=1.0)\n",
    "            YearBuilt = st.number_input('YearBuilt', min_value=1800.0, max_value=2021.0, value=1980.0)\n",
    "            PoolArea = st.number_input('PoolArea', min_value=0.0, max_value=1000.0, value=500.0)\n",
    "            PoolQC=st.selectbox('PoolQC', ['Gd', 'TA', 'Fa', 'NA'])\n",
    "            Fence = st.selectbox('Fence', ['MnPrv', 'GdWo', 'MnWw', 'NA'])\n",
    "            Utilities=st.selectbox('Utilities', ['AllPub','NoSewr', 'NoSeWa', 'ELO'])\n",
    "            MSSubClass=st.selectbox('MSSubClass', [20,30,40,45,50,60,70,75,80,85,90,120,150,160,180,190])\n",
    "            LotFrontage=st.number_input('LotFrontage', min_value=0.0, max_value=400.0, value=100.0)\n",
    "            LotArea=st.number_input('LotArea', min_value=0.0, max_value=30000.0, value=10000.0)\n",
    "            Street=st.selectbox('Street', ['Grvl','Pave'])\n",
    "            Alley=st.selectbox('Alley', ['Grvl', 'Pave', 'NA'])\n",
    "            LotShape=st.selectbox('LotShape', ['Reg', 'IR1', 'IR2', 'IR3'])\n",
    "            LandContour=st.selectbox('LandContour', ['Lvl', 'Bnk', 'HLS', 'Low'])\n",
    "            LotConfig=st.selectbox('LotConfig', ['Inside', 'Corner', 'CulDSac', 'FR2', 'FR3'])\n",
    "            Condition1=st.selectbox('Condition1', ['Artery', 'Feedr', 'Norm', 'RRNn', 'RRAn', 'PosN', 'PosA', 'RRNe', 'RRAe'])\n",
    "            Condition2=st.selectbox('Condition2', ['Artery', 'Feedr', 'Norm', 'RRNn', 'RRAn', 'PosN', 'PosA', 'RRNe', 'RRAe'])\n",
    "            BldgType=st.selectbox('BldgType', ['1Fam', '2FmCon', 'Duplx', 'TwnhsE', 'TwnhsI'])\n",
    "            HouseStyle=st.selectbox('HouseStyle', ['1Story', '1 .5Fin', '1 .5Unf', '2Story', '2 .5Fin', '2 .5Unf', 'SFoyer', 'SLvl'])\n",
    "            YearRemodAdd=st.number_input('YearRemodAdd', min_value=1800.0, max_value=2021.0, value=1980.0)\n",
    "            RoofStyle=st.selectbox('RoofStyle', ['Flat', 'Gabel', 'Gambrel', 'Hip', 'Mansard', 'Shed'])\n",
    "            RoofMatl=st.selectbox('RoofMatl', ['ClyTile', 'CompShg', 'Membran', 'Metal', 'Roll', 'Tar&Grv', 'WdShake', 'WdShngl'])\n",
    "            Exterior1st=st.selectbox('Exterior1st', ['AsbShng', 'AsphShn', 'BrkComm', 'BrkFace', 'CBlock', 'CemntBd', 'HdBoard', 'ImStucc', 'MetalSd', 'Other', 'Plywood', 'PreCast', 'Stone', 'Stucco','VinylSd','Wd Sdng', 'WdShing'])\n",
    "            Exterior2nd=st.selectbox('Exterior2nd', ['AsbShng', 'AsphShn', 'BrkComm', 'BrkFace', 'CBlock', 'CemntBd', 'HdBoard', 'ImStucc', 'MetalSd', 'Other', 'Plywood', 'PreCast', 'Stone', 'Stucco','VinylSd','Wd Sdng', 'WdShing'])\n",
    "            MasVnrType = st.selectbox('MasVnrType', ['BrkCmn', 'BrkFace', 'CBlock', 'None', 'Stone'])\n",
    "            MasVnrArea=st.number_input('MasVnrArea', min_value=0.0, value=100.0)\n",
    "            ExterQual=st.selectbox('ExterQual', ['Ex', 'Gd', 'TA', 'Fa', 'Po'])\n",
    "            ExterCond=st.selectbox('ExterCond', ['Ex', 'Gd', 'TA', 'Fa', 'Po'])\n",
    "            Foundation=st.selectbox('Foundation', ['BrkTil', 'CBlock', 'PConc', 'Slab', 'Stone', 'Wood'])\n",
    "            BsmtQual=st.selectbox('BsmtQual', ['Ex', 'Gd', 'TA', 'Fa', 'Po', 'NA'])\n",
    "            BsmtCond=st.selectbox('BsmtCond', ['Ex', 'Gd', 'TA', 'Fa', 'Po', 'NA'])\n",
    "            BsmtExposure=st.selectbox('BsmtExposure', ['Gd', 'Av', 'Mn', 'No', 'NA'])\n",
    "            BsmtFinType1=st.selectbox('BsmtFinType1', ['GLQ', 'ALQ', 'BLQ', 'Rec', 'LwQ', 'Unf', 'NA'])\n",
    "            BsmtFinSF1 = st.number_input('BsmtFinSF1', min_value=0.0, max_value=6000.0, value=500.0)\n",
    "            BsmtFinType2 = st.selectbox('BsmtFinType2', ['GLQ', 'ALQ', 'BLQ', 'Rec', 'LwQ', 'Unf', 'NA'])\n",
    "            BsmtFinSF2 = st.number_input('BsmtFinSF2', min_value=0.0, max_value=6000.0, value=500.0)\n",
    "            BsmtUnfSF =st.number_input('BsmtUnfSF', min_value=0.0, max_value=3000.0, value=500.0)\n",
    "            TotalBsmtSF = st.number_input('TotalBsmtSF', min_value=0.0, max_value=7000.0, value=1000.0)\n",
    "            Heating = st.selectbox('Heating', ['Floor','GasA','GasW ','Grav','OthW','Wall'])\n",
    "            HeatingQC = st.selectbox('HeatingQC', ['Ex', 'Gd', 'TA', 'Fa', 'Po'])\n",
    "            SaleCondition=st.selectbox('SaleCondition', ['Normal', 'Abnormal', 'AdjLand', 'Alloca', 'Family', 'Partial'])\n",
    "            SaleType=st.selectbox('SaleType', ['WD', 'CWD', 'VWD', 'New', 'COD', 'Con', 'ConLw', 'ConLI', 'ConLD', 'Oth'])\n",
    "            YrSold=st.number_input('YrSold', min_value=1950, max_value=2050, value=2010)\n",
    "            MoSold=st.selectbox('MoSold', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])\n",
    "            MiscVal=st.number_input('MiscVal', min_value=0, max_value=15500, value=5000)\n",
    "            MiscFeature=st.selectbox('MiscFeature', ['Elev', 'Gar2', 'Othr', 'Shed', 'TenC', 'NA'])\n",
    "            ScreenPorch=st.number_input('ScreenPorch', min_value=0, max_value=1000, value=250)\n",
    "            SsnPorch=st.number_input('3SsnPorch', min_value=0, max_value=1000, value=250)\n",
    "            EnclosedPorch=st.number_input('EnclosedPorch', min_value=0, max_value=1000, value=250)\n",
    "            OpenPorchSF=st.number_input('OpenPorchSF', min_value=0, max_value=1000, value=250)\n",
    "            WoodDeckSF=st.number_input('WoodDeckSF', min_value=0, max_value=1000, value=250)\n",
    "            PavedDrive=st.selectbox('PavedDrive', ['Y', 'P', 'N'])\n",
    "            GarageCond=st.selectbox('GarageCond', ['Ex', 'Gd', 'TA', 'Fa', 'Po', 'NA'])\n",
    "            GarageQual=st.selectbox('GarageQual', ['Ex', 'Gd', 'TA', 'Fa', 'Po', 'NA'])\n",
    "            GarageFinish=st.selectbox('GarageFinish', ['Fin', 'RFn', 'Unf', 'NA'])\n",
    "            GarageYrBlt=st.number_input('GarageYrBlt', min_value=1900, max_value=2050, value=1980)\n",
    "            FireplaceQu=st.selectbox('FireplaceQu', ['Ex', 'Gd', 'TA', 'Fa', 'Po', 'NA'])\n",
    "            KitchenQual=st.selectbox('KitchenQual', ['Ex', 'Gd', 'TA', 'Fa', 'Po', 'NA'])\n",
    "            KitchenAbvGr=st.number_input('KitchenAbvGr', min_value=0, max_value=10, value=2)\n",
    "            BedroomAbvGr=st.number_input('BedroomAbvGr', min_value=0, max_value=20, value=4)\n",
    "            HalfBath=st.number_input('HalfBath', min_value=0, max_value=10, value=2)\n",
    "            BsmtHalfBath=st.number_input('BsmtHalfBath', min_value=0, max_value=10, value=1)\n",
    "            BsmtFullBath=st.number_input('BsmtFullBath', min_value=0, max_value=10, value=1)\n",
    "            LowQualFinSF=st.number_input('LowQualFinSF', min_value=0, max_value=1000, value=5)\n",
    "            TwondFlrSF=st.number_input('2ndFlrSF', min_value=0, max_value=3000, value=300)\n",
    "            OnestFlrSF=st.number_input('1stFlrSF', min_value=100, max_value=6000, value=400)\n",
    "            Electrical=st.selectbox('Electrical', ['SBrkr', 'FuseA', 'FuseF', 'FuseP', 'Mix'])\n",
    "            CentralAir=st.selectbox('CentralAir', ['N', 'Y'])\n",
    "         \n",
    "            \n",
    "            \n",
    "            output=''\n",
    "            input_dict = {'OverallQual':OverallQual, 'MSZoning':MSZoning, 'GrLivArea':GrLivArea, 'OverallCond':OverallCond, \n",
    "                          'GarageType':GarageType, 'LandSlope':LandSlope, 'FullBath':FullBath, 'Neighborhood':Neighborhood, \n",
    "                          'Functional':Functional, 'MSSubClass':MSSubClass, 'LotFrontage':LotFrontage, 'LotArea':LotArea, 'Street':Street,'Alley':Alley,\n",
    "                          'LotShape':LotShape,'LandContour':LandContour,'Utilities':Utilities,'LotConfig':LotConfig,'Condition1': Condition1,\n",
    "                          'Condition2': Condition2,'BldgType':BldgType,'HouseStyle':HouseStyle,'YearBuilt':YearBuilt,'YearRemodAdd':YearRemodAdd,'RoofStyle':RoofStyle,\n",
    "                          'RoofMatl':RoofMatl,'Exterior1st':Exterior1st ,'Exterior2nd':Exterior2nd,'MasVnrType':MasVnrType,'MasVnrArea':MasVnrArea,'ExterQual':ExterQual,\n",
    "                          'ExterCond':ExterCond,'Foundation':Foundation,'BsmtQual':BsmtQual,'BsmtCond':BsmtCond,'BsmtExposure':BsmtExposure,'BsmtFinType1':BsmtFinType1,\n",
    "                          'BsmtFinSF1':BsmtFinSF1,'BsmtFinType2':BsmtFinType2,'BsmtFinSF2':BsmtFinSF2,'BsmtUnfSF':BsmtUnfSF,'TotalBsmtSF':TotalBsmtSF,'Heating':Heating,'HeatingQC':HeatingQC, \n",
    "                          'CentralAir':CentralAir,'Electrical':Electrical,'1stFlrSF':OnestFlrSF, '2ndFlrSF':TwondFlrSF,'LowQualFinSF':LowQualFinSF,'BsmtFullBath':BsmtFullBath,'BsmtHalfBath':BsmtHalfBath,\n",
    "                          'HalfBath':HalfBath,'BedroomAbvGr':BedroomAbvGr,'KitchenAbvGr':KitchenAbvGr,'KitchenQual':KitchenQual,'TotRmsAbvGrd':TotRmsAbvGrd, 'Fireplaces':Fireplaces,'FireplaceQu':FireplaceQu,\n",
    "                          'GarageYrBlt':GarageYrBlt, 'GarageFinish':GarageFinish,'GarageCars':GarageCars, 'GarageArea':GarageArea, 'GarageQual':GarageQual,'GarageCond':GarageCond,'PavedDrive':PavedDrive,\n",
    "                          'WoodDeckSF':WoodDeckSF,'OpenPorchSF':OpenPorchSF,'EnclosedPorch':EnclosedPorch,'3SsnPorch':SsnPorch,'ScreenPorch':ScreenPorch,'PoolArea':PoolArea,'PoolQC':PoolQC,'Fence':Fence,\n",
    "                          'MiscFeature':MiscFeature,'MiscVal':MiscVal, 'MoSold':MoSold, 'YrSold':YrSold, 'SaleType':SaleType,'SaleCondition':SaleCondition}\n",
    "           \n",
    "            input_df = pd.DataFrame(input_dict, index=[0])\n",
    "        \n",
    "            if st.button('Predict'): \n",
    "                output = self.predict(input_df)\n",
    "                self.store_prediction(output)\n",
    "                \n",
    "               \n",
    "                output = output['Label'][0]\n",
    "                \n",
    "            \n",
    "            st.success('Predicted output: ${}'.format(output))\n",
    "            \n",
    "        if add_selectbox == 'Batch': \n",
    "            fn = st.file_uploader(\"Upload csv file for predictions\") #st.file_uploader('Upload csv file for predictions, type=[\"csv\"]')\n",
    "            if fn is not None: \n",
    "                input_df = pd.read_csv(fn)\n",
    "                predictions = self.predict(input_df)\n",
    "                st.write(predictions)\n",
    "            \n",
    "sa = StreamlitApp()\n",
    "sa.run()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
